### ISSUE TITLE
Cannot pip install flask-yeoman

### ISSUE THREAD

**Issue by thathert** [tsileo/flask-yeoman#1]
I'm getting the following log output after failing to run `pip install flask-yeoman`

```
------------------------------------------------------------
/usr/local/bin/pip run on Sat Jul 26 15:17:04 2014
Downloading/unpacking flask-yeoman
Getting page https://pypi.python.org/simple/flask-yeoman/
URLs to search for versions for flask-yeoman:
* https://pypi.python.org/simple/flask-yeoman/
Analyzing links from page https://pypi.python.org/simple/flask-yeoman/
Could not find any downloads that satisfy the requirement flask-yeoman
Cleaning up...
Removing temporary dir /private/var/folders/c9/qlnmc27n5tz_wmhrt4_khkk00000gp/T/pip_build_jhert...
No distributions at all found for flask-yeoman
Exception information:
Traceback (most recent call last):
File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for flask-yeoman
```

**Comment by minhoryang** [comment]
+1 me too.

**Comment by colmoneill** [comment]
I'm getting this as an issue also, any ideas? Cheers!
